import { db } from '@/db';
import { tasks } from '@/db/schema';

async function main() {
    const sampleTasks = [
        {
            title: 'Complete project proposal',
            description: 'Draft and finalize the Q2 project proposal including budget estimates and timeline.',
            status: 'in-progress',
            priority: 'high',
            dueDate: new Date('2024-02-15').toISOString(),
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            title: 'Review code changes',
            description: null,
            status: 'todo',
            priority: 'medium',
            dueDate: new Date('2024-02-08').toISOString(),
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'Update documentation',
            description: 'Update API documentation to reflect recent endpoint changes and add examples.',
            status: 'done',
            priority: 'low',
            dueDate: null,
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            title: 'Plan marketing campaign',
            description: 'Create comprehensive marketing strategy for product launch including social media, email, and content marketing.',
            status: 'todo',
            priority: 'high',
            dueDate: new Date('2024-02-20').toISOString(),
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            title: 'Fix bug in login system',
            description: 'Investigate and resolve authentication timeout issue reported by multiple users.',
            status: 'in-progress',
            priority: 'high',
            dueDate: new Date('2024-01-28').toISOString(),
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            title: 'Write unit tests',
            description: null,
            status: 'todo',
            priority: 'medium',
            dueDate: new Date('2024-02-12').toISOString(),
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            title: 'Design new homepage',
            description: 'Create modern, responsive homepage design with improved user experience and conversion optimization.',
            status: 'in-progress',
            priority: 'medium',
            dueDate: new Date('2024-02-25').toISOString(),
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'Prepare quarterly report',
            description: 'Compile Q1 performance metrics and create presentation for stakeholders.',
            status: 'todo',
            priority: 'high',
            dueDate: new Date('2024-01-25').toISOString(),
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            title: 'Schedule team meeting',
            description: null,
            status: 'done',
            priority: 'low',
            dueDate: null,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            title: 'Update security protocols',
            description: 'Review and update company security policies and implement new password requirements.',
            status: 'in-progress',
            priority: 'medium',
            dueDate: new Date('2024-02-10').toISOString(),
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            title: 'Research new technologies',
            description: 'Evaluate potential new frameworks and tools for upcoming projects.',
            status: 'todo',
            priority: 'low',
            dueDate: null,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            title: 'Create user onboarding flow',
            description: 'Design and implement step-by-step onboarding process for new users.',
            status: 'in-progress',
            priority: 'medium',
            dueDate: new Date('2024-02-18').toISOString(),
            createdAt: new Date('2024-01-09').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            title: 'Optimize database queries',
            description: null,
            status: 'done',
            priority: 'medium',
            dueDate: new Date('2024-01-20').toISOString(),
            createdAt: new Date('2024-01-03').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            title: 'Implement dark mode',
            description: 'Add dark theme support across all application components with user preference persistence.',
            status: 'todo',
            priority: 'low',
            dueDate: new Date('2024-03-01').toISOString(),
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            title: 'Test mobile responsiveness',
            description: 'Comprehensive testing of mobile layout and functionality across different devices.',
            status: 'in-progress',
            priority: 'medium',
            dueDate: new Date('2024-02-05').toISOString(),
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            title: 'Refactor authentication system',
            description: 'Modernize auth system with improved security and better user experience.',
            status: 'todo',
            priority: 'high',
            dueDate: new Date('2024-02-28').toISOString(),
            createdAt: new Date('2024-01-07').toISOString(),
            updatedAt: new Date('2024-01-07').toISOString(),
        },
        {
            title: 'Deploy staging environment',
            description: null,
            status: 'done',
            priority: 'medium',
            dueDate: null,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            title: 'Setup monitoring alerts',
            description: 'Configure comprehensive monitoring and alerting for production systems.',
            status: 'todo',
            priority: 'medium',
            dueDate: new Date('2024-02-14').toISOString(),
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            title: 'Review PR #123',
            description: null,
            status: 'done',
            priority: 'low',
            dueDate: new Date('2024-01-22').toISOString(),
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            title: 'Update API documentation',
            description: 'Add missing endpoints documentation and update existing examples with current response formats.',
            status: 'todo',
            priority: 'low',
            dueDate: null,
            createdAt: new Date('2024-01-06').toISOString(),
            updatedAt: new Date('2024-01-06').toISOString(),
        }
    ];

    await db.insert(tasks).values(sampleTasks);
    
    console.log('✅ Tasks seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});