import { db } from '@/db';
import { tasks } from '@/db/schema';

async function main() {
    const sampleTasks = [
        {
            id: 'task-1',
            title: 'Complete project proposal',
            notes: 'Draft and finalize the Q2 project proposal including budget estimates and timeline.',
            completed: 0,
            dueDate: new Date('2024-02-15').toISOString(),
            createdAt: new Date('2024-01-10').getTime(),
            updatedAt: new Date('2024-01-25').getTime(),
        },
        {
            id: 'task-2',
            title: 'Review code changes',
            notes: null,
            completed: 0,
            dueDate: new Date('2024-02-08').toISOString(),
            createdAt: new Date('2024-01-15').getTime(),
            updatedAt: new Date('2024-01-15').getTime(),
        },
        {
            id: 'task-3',
            title: 'Update documentation',
            notes: 'Update API documentation to reflect recent endpoint changes and add examples.',
            completed: 1,
            dueDate: null,
            createdAt: new Date('2024-01-08').getTime(),
            updatedAt: new Date('2024-01-30').getTime(),
        },
        {
            id: 'task-4',
            title: 'Plan marketing campaign',
            notes: 'Create comprehensive marketing strategy for product launch including social media, email, and content marketing.',
            completed: 0,
            dueDate: new Date('2024-02-20').toISOString(),
            createdAt: new Date('2024-01-12').getTime(),
            updatedAt: new Date('2024-01-12').getTime(),
        },
        {
            id: 'task-5',
            title: 'Fix bug in login system',
            notes: 'Investigate and resolve authentication timeout issue reported by multiple users.',
            completed: 0,
            dueDate: new Date('2024-01-28').toISOString(),
            createdAt: new Date('2024-01-20').getTime(),
            updatedAt: new Date('2024-01-26').getTime(),
        },
        {
            id: 'task-6',
            title: 'Write unit tests',
            notes: null,
            completed: 0,
            dueDate: new Date('2024-02-12').toISOString(),
            createdAt: new Date('2024-01-18').getTime(),
            updatedAt: new Date('2024-01-18').getTime(),
        },
        {
            id: 'task-7',
            title: 'Design new homepage',
            notes: 'Create modern, responsive homepage design with improved user experience and conversion optimization.',
            completed: 0,
            dueDate: new Date('2024-02-25').toISOString(),
            createdAt: new Date('2024-01-05').getTime(),
            updatedAt: new Date('2024-01-28').getTime(),
        },
        {
            id: 'task-8',
            title: 'Prepare quarterly report',
            notes: 'Compile Q1 performance metrics and create presentation for stakeholders.',
            completed: 0,
            dueDate: new Date('2024-01-25').toISOString(),
            createdAt: new Date('2024-01-16').getTime(),
            updatedAt: new Date('2024-01-16').getTime(),
        },
        {
            id: 'task-9',
            title: 'Schedule team meeting',
            notes: null,
            completed: 1,
            dueDate: null,
            createdAt: new Date('2024-01-22').getTime(),
            updatedAt: new Date('2024-01-23').getTime(),
        },
        {
            id: 'task-10',
            title: 'Update security protocols',
            notes: 'Review and update company security policies and implement new password requirements.',
            completed: 0,
            dueDate: new Date('2024-02-10').toISOString(),
            createdAt: new Date('2024-01-14').getTime(),
            updatedAt: new Date('2024-01-27').getTime(),
        },
        {
            id: 'task-11',
            title: 'Research new technologies',
            notes: 'Evaluate potential new frameworks and tools for upcoming projects.',
            completed: 0,
            dueDate: null,
            createdAt: new Date('2024-01-11').getTime(),
            updatedAt: new Date('2024-01-11').getTime(),
        },
        {
            id: 'task-12',
            title: 'Create user onboarding flow',
            notes: 'Design and implement step-by-step onboarding process for new users.',
            completed: 0,
            dueDate: new Date('2024-02-18').toISOString(),
            createdAt: new Date('2024-01-09').getTime(),
            updatedAt: new Date('2024-01-29').getTime(),
        },
        {
            id: 'task-13',
            title: 'Optimize database queries',
            notes: null,
            completed: 1,
            dueDate: new Date('2024-01-20').toISOString(),
            createdAt: new Date('2024-01-03').getTime(),
            updatedAt: new Date('2024-01-19').getTime(),
        },
        {
            id: 'task-14',
            title: 'Implement dark mode',
            notes: 'Add dark theme support across all application components with user preference persistence.',
            completed: 0,
            dueDate: new Date('2024-03-01').toISOString(),
            createdAt: new Date('2024-01-13').getTime(),
            updatedAt: new Date('2024-01-13').getTime(),
        },
        {
            id: 'task-15',
            title: 'Test mobile responsiveness',
            notes: 'Comprehensive testing of mobile layout and functionality across different devices.',
            completed: 0,
            dueDate: new Date('2024-02-05').toISOString(),
            createdAt: new Date('2024-01-17').getTime(),
            updatedAt: new Date('2024-01-26').getTime(),
        },
        {
            id: 'task-16',
            title: 'Refactor authentication system',
            notes: 'Modernize auth system with improved security and better user experience.',
            completed: 0,
            dueDate: new Date('2024-02-28').toISOString(),
            createdAt: new Date('2024-01-07').getTime(),
            updatedAt: new Date('2024-01-07').getTime(),
        },
        {
            id: 'task-17',
            title: 'Deploy staging environment',
            notes: null,
            completed: 1,
            dueDate: null,
            createdAt: new Date('2024-01-19').getTime(),
            updatedAt: new Date('2024-01-24').getTime(),
        },
        {
            id: 'task-18',
            title: 'Setup monitoring alerts',
            notes: 'Configure comprehensive monitoring and alerting for production systems.',
            completed: 0,
            dueDate: new Date('2024-02-14').toISOString(),
            createdAt: new Date('2024-01-21').getTime(),
            updatedAt: new Date('2024-01-21').getTime(),
        },
        {
            id: 'task-19',
            title: 'Review PR #123',
            notes: null,
            completed: 1,
            dueDate: new Date('2024-01-22').toISOString(),
            createdAt: new Date('2024-01-21').getTime(),
            updatedAt: new Date('2024-01-22').getTime(),
        },
        {
            id: 'task-20',
            title: 'Update API documentation',
            notes: 'Add missing endpoints documentation and update existing examples with current response formats.',
            completed: 0,
            dueDate: null,
            createdAt: new Date('2024-01-06').getTime(),
            updatedAt: new Date('2024-01-06').getTime(),
        }
    ];

    await db.insert(tasks).values(sampleTasks);
    
    console.log('✅ Tasks seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});